### ISSUE TITLE
forge (mobile): footer squished

### ISSUE THREAD

**Issue by henry-rong** [iforge-uos/ignis#9]
The front page has an ugly gap running along the right side. This is due to a footer with crowded elements. 

A mobile footer is needed. Device of screenshot: Google Pixel 6A

![Screenshot_20240927-004758.png](https://github.com/user-attachments/assets/38fcefb1-ebeb-4c69-b538-91b247664e80)

**Comment by henry-rong** [comment]
I hope you folks don't mind me raising issues for mobile devices. Methinks most users would experience this site on a mobile device 📱

**Comment by Sampiiiii** [comment]
Fixed
